
import { WritingTemplate, UsefulSentence, WritingSkill } from '../types';

// 1. 万能开头 (Opening Masterclass) - 深度扩容 (35条)
export const OPENING_MASTER: WritingTemplate[] = [
  { category: '背景描述', title: '科技进步双刃剑', content: 'In recent years, the rapid advancement of technology has significantly reshaped our lives, bringing both unprecedented convenience and complex challenges.', scene: '互联网/AI/生活方式' },
  { category: '格言引入', title: '勤奋与成功', content: 'As the famous proverb goes, "No pains, no gains." This timeless wisdom underscores the fundamental role of hard work in achieving one\'s goals.', scene: '励志/个人成长' },
  { category: '现象对比', title: '双重观点切入', content: 'When it comes to [Topic], people\'s perspectives vary widely. While some argue that..., others maintain a contrasting view that...', scene: '争议话题' },
  { category: '背景描述', title: '信息爆炸时代', content: 'We are currently living in an era characterized by an explosion of information, where discerning truth from falsehood has become a vital skill.', scene: '教育/媒体' },
  { category: '校园生活', title: '大学生就业观', content: 'Nowadays, a growing number of college students are shifting their career focus from traditional stability to entrepreneurial ventures.', scene: '就业/创业' },
  { category: '环保话题', title: '绿色生活方式', content: 'With environmental degradation becoming an increasingly pressing global concern, the concept of a low-carbon lifestyle has gained immense popularity.', scene: '环保/低碳' },
  { category: '心理健康', title: '学术压力挑战', content: 'The intensifying competition in modern society has placed a heavy psychological burden on college students, sparking widespread concern about mental health.', scene: '压力/心理' },
  { category: '社会热点', title: '社交媒体依赖', content: 'The prevalence of social media platforms has revolutionized how we communicate, yet it has also raised concerns about privacy and social alienation.', scene: '社交网络' },
  { category: '传统文化', title: '文化传承重要性', content: 'In the process of modernization, preserving our cultural heritage has become more significant than ever for maintaining our national identity.', scene: '文化/艺术' },
  { category: '应用文', title: '感谢信开头', content: 'I am writing this letter to express my deepest gratitude for the generous assistance you provided during my academic exchange program.', scene: '感谢信' },
  { category: '应用文', title: '投诉信开头', content: 'I am writing to formally complain about the poor quality of the product I recently purchased from your online store.', scene: '投诉信' },
  { category: '应用文', title: '建议信开头', content: 'I am a frequent user of your library, and I am writing to offer some constructive suggestions regarding the improvement of its facilities.', scene: '建议信' },
  { category: '现象描述', title: '碎片化阅读', content: 'The trend of fragmented reading has become a prominent feature of the digital age, profoundly affecting our ability for deep concentration.', scene: '阅读/学习' },
  { category: '背景铺垫', title: '全球化浪潮', content: 'Under the wave of globalization, cross-cultural communication has become an indispensable part of our daily life and career development.', scene: '英语学习/交流' },
  { category: '引经据典', title: '知识的力量', content: 'Sir Francis Bacon once remarked, "Knowledge is power." In today\'s knowledge-based economy, this statement rings truer than ever.', scene: '教育/技能' },
  { category: '现象描述', title: '过度消费', content: 'The phenomenon of over-consumption among young people has triggered heated discussions about the essence of a meaningful life.', scene: '消费观/生活态度' },
  { category: '背景铺垫', title: '教育改革', content: 'Against the backdrop of educational reform, fostering critical thinking skills has replaced rote memorization as a primary goal for many universities.', scene: '教育/大学' },
  { category: '现象描述', title: '远程办公', content: 'The sudden shift towards remote work has fundamentally challenged our traditional understanding of the office environment and work-life balance.', scene: '职业/科技' },
  { category: '社会现象', title: '数字鸿沟', content: 'The digital divide has emerged as a significant social issue, creating disparities in access to information and opportunities across different demographics.', scene: '科技/社会' },
  { category: '教育话题', title: '终身学习理念', content: 'In an era of rapid technological advancement, the concept of lifelong learning has become more crucial than ever for personal and professional development.', scene: '学习/职业' },
  { category: '健康生活', title: '运动与健康', content: 'As sedentary lifestyles become increasingly common, the importance of regular physical exercise in maintaining both physical and mental well-being cannot be overstated.', scene: '健康/运动' },
  { category: '人际关系', title: '友谊的价值', content: 'In our fast-paced modern society, genuine friendships have become increasingly precious, serving as emotional anchors in times of uncertainty.', scene: '友谊/人际' },
  { category: '创新创业', title: '创新思维', content: 'Innovation has become the driving force behind economic growth, making creative thinking an essential skill for the next generation of leaders.', scene: '创新/商业' },
  { category: '时间管理', title: '效率与平衡', content: 'The art of time management has become a critical life skill, as individuals struggle to balance productivity with personal well-being in our demanding world.', scene: '效率/生活' },
  { category: '应用文', title: '邀请信开头', content: 'It is my great pleasure to invite you to participate in our upcoming cultural exchange program, which promises to be both educational and enriching.', scene: '邀请信' },
  { category: '应用文', title: '申请信开头', content: 'I am writing to express my strong interest in applying for the position of student ambassador at your esteemed institution.', scene: '申请信' },
  { category: '社会责任', title: '公民意识', content: 'In today\'s interconnected world, developing a strong sense of civic responsibility has become essential for creating a harmonious and sustainable society.', scene: '社会/责任' },
  { category: '科技伦理', title: '人工智能挑战', content: 'As artificial intelligence continues to advance at an unprecedented pace, society faces complex ethical questions about the role of technology in human life.', scene: 'AI/伦理' },
  { category: '文化交流', title: '多元文化', content: 'Cultural diversity has become one of our greatest assets in the globalized world, fostering creativity and mutual understanding among different communities.', scene: '文化/国际' },
  { category: '经济发展', title: '可持续发展', content: 'The pursuit of sustainable development has become a global priority, requiring a delicate balance between economic growth and environmental protection.', scene: '经济/环保' },
  { category: '代际差异', title: '数字原住民', content: 'The emergence of digital natives has created a significant generational gap, fundamentally changing how different age groups perceive and interact with technology.', scene: '代际/科技' },
  { category: '职业规划', title: '未来职场', content: 'The rapidly evolving job market demands that today\'s students develop adaptable skills and embrace continuous learning to remain competitive in their careers.', scene: '职业/未来' },
  { category: '心理健康', title: '压力管理', content: 'Mental health awareness has gained unprecedented attention in recent years, highlighting the importance of stress management and emotional well-being.', scene: '心理/健康' },
  { category: '社交媒体', title: '虚拟与现实', content: 'The blurring lines between virtual and real-world interactions have fundamentally altered how we form relationships and perceive social connections.', scene: '社交/网络' },
  { category: '学习方法', title: '个性化教育', content: 'The shift towards personalized learning approaches has revolutionized education, recognizing that each student has unique strengths and learning preferences.', scene: '教育/个性化' }
];

// 2. 逻辑衔接与中间段提分 (Body & Connectors) - 深度扩容 (40条)
export const BODY_CONNECTORS: WritingSkill[] = [
  { group: 'logic', title: '有序罗列 (LV1)', usage: '用于列举第一、第二、第三点。', example: 'To begin with, ...; In addition, ...; Last but not least, ...', chinese: '首先；此外；最后。' },
  { group: 'logic', title: '因果转换 (LV2)', usage: '替换 simple because。', example: 'One major reason behind this phenomenon is that... Consequently, ...', chinese: '这背后的一个主要原因是... 因此...' },
  { group: 'logic', title: '转折对比 (LV2)', usage: '体现辩证思考。', example: 'Admittedly, [A] has its merits. However, it is undeniable that [B] is more effective.', chinese: '诚然，A有其优点。然而，不可否认的是B更有效。' },
  { group: 'structure', title: '虚拟语气 (LV3)', usage: '极高提分点！建议用在分析问题时。', example: 'If we had realized the seriousness of the problem earlier, we would not be in such a dilemma now.', chinese: '如果我们早点意识到问题的严重性，现在就不会处于这种困境中了。' },
  { group: 'structure', title: '倒装句 (LV3)', usage: '展示语法驾驭能力。', example: 'Only by cooperating with each other can we overcome the difficulties in the path of progress.', chinese: '只有相互合作，我们才能克服前进道路上的困难。' },
  { group: 'structure', title: '强调句 (LV3)', usage: '突出核心论点。', example: 'It is the persistent effort, rather than mere luck, that leads to ultimate success.', chinese: '正是持之以恒的努力，而非仅仅是运气，才导致了最终的成功。' },
  { group: 'vocabulary', title: '举例说明 (LV1)', usage: '具体化论点。', example: 'A case in point is that many successful entrepreneurs attribute their achievements to early failures.', chinese: '一个恰当的例子是，许多成功的企业家将他们的成就归功于早期的失败。' },
  { group: 'logic', title: '递进强调 (LV2)', usage: '由浅入深论证。', example: 'Not only does it enrich our professional knowledge, but it also broadens our global horizons.', chinese: '它不仅丰富了我们的专业知识，还拓宽了我们的国际视野。' },
  { group: 'structure', title: '非谓语动词 (LV3)', usage: '精炼句式。', example: 'Compared with traditional methods, online learning offers unparalleled flexibility and convenience.', chinese: '与传统方法相比，在线学习提供了无与伦比的灵活性和便利。' },
  { group: 'logic', title: '总结原因', usage: '段落末尾收束。', example: 'Taking all these factors into account, it is safe to conclude that the root cause lies in...', chinese: '考虑到所有这些因素，可以有把握地得出结论，根本原因在于...' },
  { group: 'vocabulary', title: '引用研究', usage: '增强说服力。', example: 'According to a recent survey conducted by [Institution], nearly 70% of participants expressed their support for...', chinese: '根据最近由某机构进行的一项调查，近70%的参与者表示支持...' },
  { group: 'logic', title: '比较关系', usage: '用于优劣分析。', example: 'The advantages of reading classics far outweigh its potential disadvantages.', chinese: '阅读名著的优点远胜于其潜在的缺点。' },
  { group: 'structure', title: '让步状语', usage: '展示从句掌握。', example: 'Even though we face numerous obstacles, we should never give up on our dreams.', chinese: '尽管我们面临重重障碍，我们也不应该放弃梦想。' },
  { group: 'logic', title: '引出下文', usage: '段间衔接。', example: 'In light of the issues mentioned above, it is essential to explore some effective solutions.', chinese: '鉴于上述提到的问题，探索一些有效的解决方案是至关重要的。' },
  { group: 'vocabulary', title: '表达影响', usage: '分析后果。', example: 'Undoubtedly, this trend exerts a profound impact on the sustainable development of our society.', chinese: '毫无疑问，这一趋势对我们社会的可持续发展产生深远影响。' },
  { group: 'structure', title: '同位语从句', usage: '解释抽象名词。', example: 'The fact that AI is changing our life is undeniable.', chinese: '人工智能正在改变我们生活这一事实是不可否认的。' },
  { group: 'logic', title: '层层递进', usage: '排比气势。', example: 'Furthermore, it is worth noting that persistent learning is the soul of personal growth.', chinese: '此外，值得注意的是，持续学习是个人成长的灵魂。' },
  { group: 'logic', title: '结果导向', usage: '最后结论。', example: 'As a result, we should raise public awareness regarding environmental protection.', chinese: '因此，我们应该提高公众的环保意识。' },
  { group: 'structure', title: '定语从句 (LV2)', usage: '丰富句式结构。', example: 'Students who actively participate in extracurricular activities tend to develop better social skills.', chinese: '积极参与课外活动的学生往往能培养更好的社交技能。' },
  { group: 'logic', title: '条件假设', usage: '分析可能性。', example: 'Provided that we take immediate action, the environmental crisis can still be mitigated.', chinese: '只要我们立即采取行动，环境危机仍然可以得到缓解。' },
  { group: 'vocabulary', title: '数据支撑', usage: '增强论证力度。', example: 'Statistics reveal that approximately 80% of college graduates prefer flexible working arrangements.', chinese: '统计数据显示，大约80%的大学毕业生更喜欢灵活的工作安排。' },
  { group: 'structure', title: '分词结构 (LV3)', usage: '高级语法展示。', example: 'Having realized the importance of teamwork, students began to collaborate more effectively.', chinese: '意识到团队合作的重要性后，学生们开始更有效地合作。' },
  { group: 'logic', title: '对比分析', usage: '突出差异。', example: 'In contrast to previous generations, today\'s youth are more environmentally conscious.', chinese: '与前几代人相比，今天的年轻人更有环保意识。' },
  { group: 'vocabulary', title: '专家观点', usage: '权威支持。', example: 'Leading experts in the field argue that sustainable development requires collective effort.', chinese: '该领域的顶尖专家认为，可持续发展需要集体努力。' },
  { group: 'structure', title: '独立主格 (LV3)', usage: '展示高级语法。', example: 'Weather permitting, the outdoor graduation ceremony will proceed as scheduled.', chinese: '天气允许的话，户外毕业典礼将按计划进行。' },
  { group: 'logic', title: '时间顺序', usage: '叙述发展过程。', example: 'Initially, the project faced numerous challenges. Subsequently, through persistent efforts, significant progress was made.', chinese: '最初，该项目面临诸多挑战。随后，通过不懈努力，取得了重大进展。' },
  { group: 'vocabulary', title: '趋势描述', usage: '分析发展方向。', example: 'There is a growing tendency among young people to prioritize work-life balance over high salaries.', chinese: '年轻人中越来越倾向于优先考虑工作与生活的平衡，而非高薪。' },
  { group: 'structure', title: '省略句 (LV2)', usage: '简洁有力表达。', example: 'When necessary, students should seek help from their professors.', chinese: '必要时，学生应该向教授寻求帮助。' },
  { group: 'logic', title: '原因分析', usage: '深入探讨根源。', example: 'The underlying reason for this phenomenon can be attributed to rapid social changes.', chinese: '这一现象的根本原因可以归因于快速的社会变化。' },
  { group: 'vocabulary', title: '现状描述', usage: '客观陈述事实。', example: 'Currently, there exists a significant gap between theoretical knowledge and practical application.', chinese: '目前，理论知识与实际应用之间存在显著差距。' },
  { group: 'structure', title: '插入语 (LV2)', usage: '补充说明信息。', example: 'This approach, though challenging, proves to be highly effective in the long run.', chinese: '这种方法虽然具有挑战性，但从长远来看证明是非常有效的。' },
  { group: 'logic', title: '重要性强调', usage: '突出关键点。', example: 'It cannot be overemphasized that education plays a crucial role in personal development.', chinese: '怎么强调都不过分的是，教育在个人发展中起着至关重要的作用。' },
  { group: 'vocabulary', title: '问题识别', usage: '指出关键问题。', example: 'One of the most pressing issues facing modern society is the widening income inequality.', chinese: '现代社会面临的最紧迫问题之一是不断扩大的收入不平等。' },
  { group: 'structure', title: '并列结构 (LV2)', usage: '平行表达增强气势。', example: 'Success requires not only talent and hard work, but also perseverance and adaptability.', chinese: '成功不仅需要天赋和努力，还需要毅力和适应能力。' },
  { group: 'logic', title: '解决方案', usage: '提出建设性建议。', example: 'To address this challenge, a multi-faceted approach involving government, businesses, and individuals is essential.', chinese: '为了应对这一挑战，需要政府、企业和个人参与的多方面方法。' },
  { group: 'vocabulary', title: '影响评估', usage: '分析长远影响。', example: 'The long-term implications of this policy change will likely reshape the entire industry landscape.', chinese: '这一政策变化的长期影响可能会重塑整个行业格局。' },
  { group: 'structure', title: '感叹句 (LV2)', usage: '表达强烈情感。', example: 'How remarkable it is that technology has transformed our daily lives so dramatically!', chinese: '科技如此戏剧性地改变了我们的日常生活，这是多么了不起啊！' },
  { group: 'logic', title: '预测未来', usage: '展望发展趋势。', example: 'It is anticipated that artificial intelligence will continue to revolutionize various sectors in the coming decades.', chinese: '预计人工智能将在未来几十年继续革命性地改变各个行业。' },
  { group: 'vocabulary', title: '挑战识别', usage: '指出面临困难。', example: 'Despite significant progress, we still face formidable challenges in achieving sustainable development goals.', chinese: '尽管取得了重大进展，我们在实现可持续发展目标方面仍面临巨大挑战。' },
  { group: 'structure', title: '反问句 (LV2)', usage: '引发思考。', example: 'Can we afford to ignore the environmental consequences of our actions any longer?', chinese: '我们还能继续忽视我们行为的环境后果吗？' }
];

// 3. 精彩结尾 (Closing Flourish) - 深度扩容 (30条)
export const CLOSING_MASTER: WritingTemplate[] = [
  { category: '总结型', title: '一语破的', content: 'In a nutshell, it is essential for us to strike a balance between individual freedom and social responsibility.', scene: '议论文/通用' },
  { category: '建议型', title: '呼吁行动', content: 'It is high time that we took effective measures to solve this pressing problem once and for all.', scene: '社会问题/环保' },
  { category: '愿景型', title: '展望未来', content: 'Only through our collective efforts can we usher in a brighter and more prosperous future for the next generation.', scene: '通用' },
  { category: '格言型', title: '名言收尾', content: 'As the old saying goes, "Where there is a will, there is a way." Let us march towards our goals with confidence.', scene: '励志' },
  { category: '应用文', title: '期待回复', content: 'I am looking forward to hearing from you at your earliest convenience. Thank you for your kind consideration.', scene: '书信' },
  { category: '观点重申', title: '坚定立场', content: 'To sum up, while the challenge is daunting, I remain firmly convinced that persistence is the key to success.', scene: '议论文' },
  { category: '反问启发', title: '引发深思', content: 'After all, if we do not cherish our environment today, what kind of world will we leave for our children?', scene: '环保/社会' },
  { category: '总结建议', title: '个人建议', content: 'In light of the above discussion, I suggest that we should cultivate a habit of lifelong learning.', scene: '教育/成长' },
  { category: '愿景型', title: '社会和谐', content: 'Let us join hands to create a more harmonious and civilized society for everyone.', scene: '社会' },
  { category: '总结型', title: '简明扼要', content: 'In conclusion, the significance of [Topic] cannot be overstated in our modern lives.', scene: '通用' },
  { category: '警告型', title: '警钟长鸣', content: 'Otherwise, we might have to pay a much higher price for our negligence in the near future.', scene: '社会/环境' },
  { category: '乐观展望', title: '充满希望', content: 'I am confident that with the joint efforts of the whole society, this issue will be resolved soon.', scene: '社会话题' },
  { category: '应用文', title: '礼貌致谢', content: 'Once again, please accept my sincere appreciation for your time and help. Best regards!', scene: '书信' },
  { category: '反思型', title: '自我提升', content: 'In short, only by constantly reflecting on our actions can we make progress in this fast-changing world.', scene: '成长' },
  { category: '号召型', title: '共同努力', content: 'It is our collective responsibility to ensure that future generations inherit a world better than the one we found.', scene: '环保/社会' },
  { category: '哲理型', title: '人生感悟', content: 'Life is a journey of continuous learning, and every challenge we face is an opportunity for growth.', scene: '人生/成长' },
  { category: '决心型', title: '坚定信念', content: 'With unwavering determination and collaborative spirit, no obstacle is insurmountable.', scene: '励志/团队' },
  { category: '应用文', title: '诚挚邀请', content: 'I sincerely hope you will consider my invitation, and I eagerly await your positive response.', scene: '邀请信' },
  { category: '应用文', title: '申请结尾', content: 'I would be honored to contribute to your organization and look forward to the opportunity to discuss my qualifications further.', scene: '申请信' },
  { category: '启发型', title: '深度思考', content: 'Perhaps it is time for us to reconsider our priorities and focus on what truly matters in life.', scene: '价值观/人生' },
  { category: '承诺型', title: '个人承诺', content: 'I pledge to do my part in addressing this challenge, and I encourage others to join me in this endeavor.', scene: '社会责任' },
  { category: '展望型', title: '科技未来', content: 'As we stand on the threshold of a new technological era, the possibilities for human advancement are limitless.', scene: '科技/未来' },
  { category: '感恩型', title: '感谢社会', content: 'We owe it to our community and society to use our knowledge and skills for the greater good.', scene: '社会贡献' },
  { category: '挑战型', title: '迎接挑战', content: 'The road ahead may be challenging, but with courage and perseverance, we can overcome any obstacle.', scene: '困难/挑战' },
  { category: '智慧型', title: '古训现用', content: 'As ancient wisdom teaches us, "A journey of a thousand miles begins with a single step."', scene: '行动/开始' },
  { category: '责任型', title: '使命担当', content: 'Each of us has a role to play in shaping a better tomorrow, and that responsibility starts today.', scene: '责任/使命' },
  { category: '平衡型', title: '和谐发展', content: 'True progress lies not in choosing between tradition and innovation, but in finding harmony between them.', scene: '传统/创新' },
  { category: '教育型', title: '学习价值', content: 'Education is not just about acquiring knowledge; it is about developing the wisdom to use that knowledge responsibly.', scene: '教育/智慧' },
  { category: '团结型', title: '合作共赢', content: 'In our interconnected world, cooperation and mutual understanding are the keys to solving global challenges.', scene: '合作/全球' },
  { category: '希望型', title: '光明前景', content: 'Despite the challenges we face today, I remain optimistic about humanity\'s capacity for positive change and innovation.', scene: '乐观/希望' }
];

// 4. 高分单词替换 (Lexical Upgrade) - 深度扩容 (50条)
export const VOCAB_UPGRADES: UsefulSentence[] = [
  { category: '核心动词', english: 'Paramount (instead of "Important")', chinese: '至高无上的', tip: 'Environmental protection is of paramount importance.' },
  { category: '核心动词', english: 'Indispensable (instead of "Necessary")', chinese: '必不可少的', tip: 'English has become an indispensable tool in our career.' },
  { category: '核心动词', english: 'Exert a profound impact (instead of "Have a big effect")', chinese: '产生深远影响', tip: 'The Internet exerts a profound impact on our education.' },
  { category: '核心动词', english: 'Alleviate (instead of "Reduce/Solve")', chinese: '减轻/缓和', tip: 'These measures help alleviate the pressure on students.' },
  { category: '核心动词', english: 'Cultivate (instead of "Build/Have")', chinese: '培养/养成', tip: 'We should cultivate a positive attitude towards difficulties.' },
  { category: '核心动词', english: 'Undeniably (instead of "Clearly")', chinese: '不可否认地', tip: 'Undeniably, technology has changed our life.' },
  { category: '核心动词', english: 'Consequence (instead of "Result")', chinese: '后果', tip: 'Pollution will have serious consequences for our health.' },
  { category: '核心动词', english: 'Acknowledge (instead of "Accept/Know")', chinese: '承认/认可', tip: 'We must acknowledge the importance of innovation.' },
  { category: '核心动词', english: 'Eliminate (instead of "Remove")', chinese: '消除/排除', tip: 'New policies aim to eliminate social inequality.' },
  { category: '核心动词', english: 'Vividly (instead of "Clearly")', chinese: '生动地', tip: 'The picture vividly describes the status of education.' },
  { category: '核心动词', english: 'Abundant (instead of "Many/Much")', chinese: '丰富的', tip: 'Our library provides abundant resources for students.' },
  { category: '核心动词', english: 'Optimize (instead of "Improve")', chinese: '优化/完善', tip: 'We need to optimize our study methods for better efficiency.' },
  { category: '核心动词', english: 'Flourish (instead of "Develop fast")', chinese: '繁荣/昌盛', tip: 'Cultural tourism is flourishing in many cities.' },
  { category: '核心动词', english: 'Hinder (instead of "Stop/Limit")', chinese: '阻碍/妨碍', tip: 'Lack of sleep can hinder our brain development.' },
  { category: '核心动词', english: 'Substitute (instead of "Change/Replace")', chinese: '替代品/替换', tip: 'Nothing can substitute for the love of family.' },
  { category: '核心动词', english: 'Endeavor (instead of "Try hard")', chinese: '努力/奋斗', tip: 'We should endeavor to achieve our goals.' },
  { category: '核心动词', english: 'Cherish (instead of "Keep/Like")', chinese: '珍惜/爱护', tip: 'Students should cherish the time spent on campus.' },
  { category: '核心动词', english: 'Acquire (instead of "Get/Learn")', chinese: '获得/取得', tip: 'College is a place to acquire both knowledge and wisdom.' },
  { category: '核心动词', english: 'Compulsory (instead of "Must-do")', chinese: '强制的/必修的', tip: 'English is a compulsory subject in our university.' },
  { category: '核心动词', english: 'Unprecedented (instead of "Never seen")', chinese: '史无前例的', tip: 'The Internet has brought about unprecedented changes.' },
  { category: '高级形容词', english: 'Compelling (instead of "Interesting")', chinese: '引人注目的/令人信服的', tip: 'The professor presented a compelling argument for renewable energy.' },
  { category: '高级形容词', english: 'Substantial (instead of "Big/Large")', chinese: '大量的/重要的', tip: 'There has been substantial progress in medical research.' },
  { category: '高级形容词', english: 'Meticulous (instead of "Careful")', chinese: '一丝不苟的', tip: 'Success requires meticulous planning and execution.' },
  { category: '高级形容词', english: 'Versatile (instead of "Useful")', chinese: '多才多艺的/多用途的', tip: 'English is a versatile language for international communication.' },
  { category: '高级形容词', english: 'Innovative (instead of "New")', chinese: '创新的', tip: 'The company is known for its innovative approach to problem-solving.' },
  { category: '高级形容词', english: 'Comprehensive (instead of "Complete")', chinese: '全面的/综合的', tip: 'Students need comprehensive knowledge to succeed in their careers.' },
  { category: '高级形容词', english: 'Rigorous (instead of "Strict")', chinese: '严格的/严谨的', tip: 'The university maintains rigorous academic standards.' },
  { category: '高级形容词', english: 'Sustainable (instead of "Long-lasting")', chinese: '可持续的', tip: 'We must adopt sustainable practices to protect our environment.' },
  { category: '高级形容词', english: 'Profound (instead of "Deep")', chinese: '深刻的/深远的', tip: 'The pandemic has had a profound effect on global education.' },
  { category: '高级形容词', english: 'Intricate (instead of "Complex")', chinese: '复杂精细的', tip: 'Understanding human behavior involves intricate psychological processes.' },
  { category: '精准动词', english: 'Facilitate (instead of "Help")', chinese: '促进/便利', tip: 'Technology can facilitate more effective learning experiences.' },
  { category: '精准动词', english: 'Demonstrate (instead of "Show")', chinese: '证明/展示', tip: 'Research demonstrates the benefits of regular exercise.' },
  { category: '精准动词', english: 'Implement (instead of "Do/Use")', chinese: '实施/执行', tip: 'Schools should implement new teaching methodologies.' },
  { category: '精准动词', english: 'Enhance (instead of "Make better")', chinese: '增强/提高', tip: 'Reading can enhance our critical thinking abilities.' },
  { category: '精准动词', english: 'Advocate (instead of "Support")', chinese: '提倡/拥护', tip: 'Many experts advocate for environmental protection measures.' },
  { category: '精准动词', english: 'Prioritize (instead of "Think important")', chinese: '优先考虑', tip: 'Students should prioritize their academic responsibilities.' },
  { category: '精准动词', english: 'Collaborate (instead of "Work together")', chinese: '合作/协作', tip: 'International teams must collaborate to solve global challenges.' },
  { category: '精准动词', english: 'Integrate (instead of "Combine")', chinese: '整合/融合', tip: 'Modern education should integrate technology with traditional methods.' },
  { category: '精准动词', english: 'Stimulate (instead of "Encourage")', chinese: '刺激/激发', tip: 'Challenging courses can stimulate intellectual growth.' },
  { category: '精准动词', english: 'Consolidate (instead of "Strengthen")', chinese: '巩固/加强', tip: 'Practice helps consolidate newly acquired knowledge.' },
  { category: '高级副词', english: 'Considerably (instead of "Very much")', chinese: '相当地/大大地', tip: 'Online learning has considerably expanded educational opportunities.' },
  { category: '高级副词', english: 'Predominantly (instead of "Mostly")', chinese: '主要地/占主导地', tip: 'The student body is predominantly composed of young adults.' },
  { category: '高级副词', english: 'Invariably (instead of "Always")', chinese: '总是/不变地', tip: 'Success invariably requires dedication and hard work.' },
  { category: '高级副词', english: 'Progressively (instead of "More and more")', chinese: '逐步地/渐进地', tip: 'Society is becoming progressively more environmentally conscious.' },
  { category: '高级副词', english: 'Fundamentally (instead of "Basically")', chinese: '根本地/基础地', tip: 'This approach is fundamentally different from traditional methods.' },
  { category: '学术表达', english: 'Empirical evidence (instead of "Proof")', chinese: '实证证据', tip: 'Empirical evidence supports the effectiveness of this teaching method.' },
  { category: '学术表达', english: 'Theoretical framework (instead of "Theory")', chinese: '理论框架', tip: 'The research is based on a solid theoretical framework.' },
  { category: '学术表达', english: 'Multifaceted approach (instead of "Many ways")', chinese: '多方面的方法', tip: 'Solving climate change requires a multifaceted approach.' },
  { category: '学术表达', english: 'Paradigm shift (instead of "Big change")', chinese: '范式转变', tip: 'Remote work represents a paradigm shift in employment practices.' },
  { category: '学术表达', english: 'Holistic perspective (instead of "Complete view")', chinese: '整体视角', tip: 'Education should adopt a holistic perspective on student development.' }
];

export const WRITING_TEMPLATES: WritingTemplate[] = [...OPENING_MASTER, ...CLOSING_MASTER];
export const WRITING_SKILLS: WritingSkill[] = BODY_CONNECTORS;
export const HIGH_SCORE_SENTENCES: UsefulSentence[] = VOCAB_UPGRADES;
